# Describes hyperparameters for TransE methods 
model: TransE

# sampling parameters
neg_strategy: [0] 
ent_neg_rate: [1]
ent_rel_rate: [0]  # All OpenKE models across all benchmarks set this to zero. 

# model specific parameters
margin: [1]
dimension: [50]
lambda: [0.0]
p_norm: [1]

# optimization parameters
opt_method: ['SGD']
lr: [0.01]
max_epochs: [1]
nbatches: [100]
early_stopping_patience: [1]
valid_steps: [501]
save_steps: [50]
nbatches: [100]
